openapi: 3.0.0
info:
  title: Demetra Catalog API
  version: 1.0.0
tags:
- name: AIModelsAPI
- name: MLClassesAPI
paths:
  /api/v1/models:
    get:
      operationId: listAIModels
      description: List AI models from ML API
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Models.AIModel'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Common.Errors.AuthenticationError'
        '403':
          description: Access is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Common.Errors.ForbiddenError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Common.Errors.InternalServerError'
      tags:
      - AIModelsAPI
      security:
      - BearerAuth: []
  /api/v1/models/by-name/{modelName}:
    get:
      operationId: getAIModelByName
      description: Get AI model by name from ML API
      parameters:
      - name: modelName
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Models.AIModel'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Common.Errors.AuthenticationError'
        '403':
          description: Access is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Common.Errors.ForbiddenError'
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Common.Errors.NotFoundError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Common.Errors.InternalServerError'
      tags:
      - AIModelsAPI
      security:
      - BearerAuth: []
components:
  schemas:
    Common.Errors.ApiError:
      type: object
      required:
      - request_id
      - message
      properties:
        request_id:
          type: string
          description: Unique identifier for the request, useful for debugging
        message:
          type: string
          description: Human-readable message describing the error
      description: All error responses share these common fields
    Common.Errors.AuthenticationError:
      type: object
      required:
      - code
      properties:
        code:
          type: string
          enum:
          - AuthenticationRequired
      allOf:
      - $ref: '#/components/schemas/Common.Errors.ApiError'
      description: Indicates that authentication is required to access the resource
    Common.Errors.ForbiddenError:
      type: object
      required:
      - code
      properties:
        code:
          type: string
          enum:
          - Forbidden
      allOf:
      - $ref: '#/components/schemas/Common.Errors.ApiError'
      description: Indicates that action is forbidden due to lack of permissions
    Common.Errors.InternalServerError:
      type: object
      required:
      - code
      properties:
        code:
          type: string
          enum:
          - InternalServerError
      allOf:
      - $ref: '#/components/schemas/Common.Errors.ApiError'
      description: Indicates that an internal server error occurred
    Common.Errors.NotFoundError:
      type: object
      required:
      - code
      - resource_id
      properties:
        code:
          type: string
          enum:
          - NotFound
        resource_id:
          type: string
          description: Identifier of the resource that was not found
      allOf:
      - $ref: '#/components/schemas/Common.Errors.ApiError'
      description: Indicates that the requested resource was not found
    Models.AIModel:
      type: object
      required:
      - modelName
      - modelType
      - isActive
      properties:
        modelName:
          type: string
          description: Model name (unique identifier)
        modelType:
          allOf:
          - $ref: '#/components/schemas/Models.AIModelType'
          description: Type of the model
        isActive:
          type: boolean
          description: Whether the model is active
      description: AI Model from ML API
    Models.AIModelType:
      type: string
      enum:
      - detection
      - classification
      - segmentation
      description: Type of AI model
  securitySchemes:
    BearerAuth:
      type: http
      scheme: Bearer
